swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  
tags:
- name: "Start Application"
  description: "Start Application"
- name: "Register"
  description: "Register services"
- name: "Event"
  description: "Events' services"
- name: "Wall Entry"
  description: "Wall Entry services"
paths:

  
  
  /api/secure/startApplication:
    # binds a127 app logic to a route
    x-swagger-router-controller: StartApplication
    get:
      tags:
       - "Start Application"
      description: Return
      # used as the method name of the controller
      operationId: startApplication
      parameters:
        - name: udid
          in: header
          description: User's udid
          required: true
          type: string
        - name: Authorization
          in: header
          description: User's authorization
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommonResponse"
  /api/registration/validateId:
   x-swagger-router-controller: Register
   post:
     tags:
      - "Register"
     operationId: registerUser
     description: User register service
     parameters:
      - name: udid
        in: header
        description: User's udid
        required: true
        type: string
      - name: registerObject
        in: body
        required: true
        schema:
         $ref: "#/definitions/RegisterObject"
     responses:
       "200":
         description: OK
         schema:
          $ref: "#/definitions/RegisterResponse"
          
  /api/registration/categories:
    x-swagger-router-controller: Register
    get:
      tags:
      - "Register"
      description: Return
      operationId: getEventsCategories
      parameters:
        - name: udid
          in: header
          description: User's udid
          required: true
          type: string
        - name: Authorization
          in: header
          description: User's authorization
          required: false
          type: string
      responses:
        "200":
          description: response
          schema:
            type: array
            items:
              $ref: "#/definitions/Interests"        
           
  /api/secure/events:
  
    x-swagger-router-controller: Event
    get:
     tags:
      - "Event"
     operationId: getEventList
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string    
     responses:
      "200":
       description: response
       schema:
        type: array
        items:
         $ref: "#/definitions/Event"
         
  /api/secure/events/{id}:
    
    x-swagger-router-controller: Event
    get:
     tags:
      - "Event"
     operationId: attendEvent
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string
      - name: id
        in: path
        type: string
        required: true
        description: Event id
     responses:
      "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommonResponse"
            
  
   
    post:
     tags:
      - "Event"
     operationId: wallEntryAdd
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string
      - name: id
        in: path
        type: string
        required: true
        description: Event id 
      - name: Wall Entry
        in: body
        required: true
        schema:
         $ref: "#/definitions/WallEntry"
     responses:
      "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommonResponse"        
            
  /api/secure/events/{id}/isAttend:
    
    x-swagger-router-controller: Event
    get:
     tags:
      - "Event"
     operationId: isAttend
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string
      - name: id
        in: path
        type: string
        required: true
        description: Event id
     responses:
      "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommonResponse"          
  
  /api/secure/events/{eventId}/wallEntries:
  
    x-swagger-router-controller: Event
    get:
     tags:
      - "Event"
     operationId: getWallEntries
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string
      - name: eventId
        in: path
        type: string
        required: true
        description: Event id
     responses:
      "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/WallEntry"
   
       
  
    
  /api/secure/events/{eventId}/wallEntry/{wallEntryId}/comments:
    
    
    x-swagger-router-controller: WallEntryService
    post:
     tags:
      - "Wall Entry"
     operationId: postComment
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string
      - name: eventId
        in: path
        type: string
        required: true
        description: Event id
      - name: wallEntryId
        in: path
        type: string
        required: true
      - name: comment
        in: body
        description: Comment object
        required: true
        schema:
         $ref: "#/definitions/Comment"
     responses:
      "200":
       description: Success
       schema:
         $ref: "#/definitions/CommonResponse"
        
    
    get:
     tags:
      - "Wall Entry"
     operationId: getComment
     parameters:
      - name: udid
        in: header
        description: User's udid
        type: string
      - name: Authorization
        in: header
        description: User's authorization
        required: false
        type: string
      - name: eventId
        in: path
        type: string
        required: true
        description: Event id
      - name: wallEntryId
        in: path
        type: string
        required: true
     responses:
      "200":
          description: Success
          schema:
            type: array
            items:
             $ref: "#/definitions/Comment"          
  

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions


definitions:



  CommonResponse:
    required:
      - code
      - message
    properties:
      code:
       type: number
      message:
        type: string
        
        
  RegisterResponse:
   required:
    - code
    - message
   properties:
    code:
     type: number
    message:
     type: string
    secret:
     type: string
     
     
     
  RegisterObject:
    properties:
     sex:
      enum: ["MALE","FEMALE"]
      type: string 
     mail:
      type: string
     age:
      type: string
     job:
      type: string
     adress:
      type: string
     interests:
      type: array
      items:
       $ref: "#/definitions/Interests"
       
  
  Interests:
   properties:
    id:
     type: string
    name:
     type: string
  
  
  Event:
   properties:
    id:
     type: string
    name:
     type: string
    description:
     type: string
    startTime:
     type: string
    endTime:
     type: string
    categoryName:
     type: string
    location:
     type: string
    
  
  WallEntry:
   properties:
    text:
     type: string
    user:
     $ref : "#/definitions/RegisterObject"
   
   
  
  Comment:
    properties:
     text:
      type: string
     user:
      $ref : "#/definitions/RegisterObject"
        
    
  
  
  
  
  
  
  
  
  
  
  
  